---
name: your name
description: what your plugin does
author: Equinix Metal
requirements:
  - if you have requirements
configuration:
  properties:
    propertyname:
      type: string
  required:
    - if any properties are required
  dependencies:
    dependencyname: [dep]