
steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.2.0:
        files:
          - hooks/**

  - label: ":rocket: Test"
    plugins:
      docker-compose#v3.7.0:
        run: tests

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: docker-login